sudo: required
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=fake-news-portal
    - ORG=g0vhk
services:
  - docker

script:
    - docker build -t $ORG/$REPO:$COMMIT portal

after_success:
    - export TAG='latest'
    - docker tag $ORG/$REPO:$COMMIT $ORG/$REPO:$TAG
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push $ORG/$REPO
